// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoQ5CVqix8adN5iGOkRcTgrg9IU1a588',
    appId: '1:1044355654409:web:25a33b855d978b395169d8',
    messagingSenderId: '1044355654409',
    projectId: 'coffeeshop-abd52',
    authDomain: 'coffeeshop-abd52.firebaseapp.com',
    storageBucket: 'coffeeshop-abd52.appspot.com',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJBEM_H_w0BvtXSZMQ8K-HDVpGUkQ7Q6g',
    appId: '1:1044355654409:android:1a8f7560e323de0e5169d8',
    messagingSenderId: '1044355654409',
    projectId: 'coffeeshop-abd52',
    storageBucket: 'coffeeshop-abd52.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_OKh4GfOuDZVawOXCTEXjcjiRjBraEY',
    appId: '1:1044355654409:ios:33e02d4adf056ccd5169d8',
    messagingSenderId: '1044355654409',
    projectId: 'coffeeshop-abd52',
    storageBucket: 'coffeeshop-abd52.appspot.com',
    iosClientId: '1044355654409-3s1ivq7rqg9546ochpo2uus79r76bauu.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShopAppUi',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_OKh4GfOuDZVawOXCTEXjcjiRjBraEY',
    appId: '1:1044355654409:ios:33e02d4adf056ccd5169d8',
    messagingSenderId: '1044355654409',
    projectId: 'coffeeshop-abd52',
    storageBucket: 'coffeeshop-abd52.appspot.com',
    iosClientId: '1044355654409-3s1ivq7rqg9546ochpo2uus79r76bauu.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeShopAppUi',
  );
}
